export const incidentDataNam = [
  {
    incident: "INC23975624",
    severity: "P1",
    status: "In Progress",
    application: "FLApp1",
    agingHours: "2",
    serverName: "uks-yf738",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975634",
    severity: "P2",
    status: "In Progress",
    application: "FLApp2",
    agingHours: "3",
    serverName: "nrw-yf738",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975644",
    severity: "P3",
    status: "In Progress",
    application: "FLApp3",
    agingHours: "4",
    serverName: "nrw-yhdfb",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975654",
    severity: "P4",
    status: "In Progress",
    application: "FLApp4",
    agingHours: "5",
    serverName: "nrw-yq2423b",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975664",
    severity: "P5",
    status: "In Progress",
    application: "FLApp5",
    agingHours: "6",
    serverName: "nrw-yf738",
    assignedTo: "John Doe",
  },
];

export const incidentDataLatam = [
  {
    incident: "INC23975624",
    severity: "P1",
    status: "In Progress",
    application: "LatamApp1",
    agingHours: "2",
    serverName: "uks-yf738",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975634",
    severity: "P2",
    status: "In Progress",
    application: "LatamApp2",
    agingHours: "3",
    serverName: "nrw-yf738",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975644",
    severity: "P3",
    status: "In Progress",
    application: "LatamApp3",
    agingHours: "4",
    serverName: "nrw-yhdfb",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975654",
    severity: "P4",
    status: "In Progress",
    application: "LatamApp4",
    agingHours: "5",
    serverName: "nrw-yq2423b",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975664",
    severity: "P5",
    status: "In Progress",
    application: "LatamApp5",
    agingHours: "6",
    serverName: "nrw-yf738",
    assignedTo: "John Doe",
  },
];

export const incidentDataApac = [
  {
    incident: "INC23975624",
    severity: "P1",
    status: "In Progress",
    application: "ApacApp1",
    agingHours: "2",
    serverName: "uks-yf738",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975634",
    severity: "P2",
    status: "In Progress",
    application: "ApacApp2",
    agingHours: "3",
    serverName: "nrw-yf738",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975644",
    severity: "P3",
    status: "In Progress",
    application: "ApacApp3",
    agingHours: "4",
    serverName: "nrw-yhdfb",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975654",
    severity: "P4",
    status: "In Progress",
    application: "ApacApp4",
    agingHours: "5",
    serverName: "nrw-yq2423b",
    assignedTo: "John Doe",
  },
  {
    incident: "INC23975664",
    severity: "P5",
    status: "In Progress",
    application: "ApacApp5",
    agingHours: "6",
    serverName: "nrw-yf738",
    assignedTo: "John Doe",
  },
];
